### ISSUE TITLE
PAPER and INK colours for each specific window.

### ISSUE THREAD

**Issue by rockersuke** [nataliapc/msx2daad#11]
In the original DAAD, PAPER and INK condacts apply only for the currently selected window and are presumably stored somewhere. It seems not to be the case in msx2daad. If I change colours in window 2, for example, they'll still be active when I get back to window 1 (or any other window).

**Comment by nataliapc** [comment]
You are right. Thanks for your comment.
Fixed!

The fix only works on fixed palette mode (screen 8), for the paletted modes (5, 6 & 7) the PAPER and INK colors remains globals.
