### ISSUE TITLE
ISDONE/ISNOTDONE mechanics not working properly

### ISSUE THREAD

**Issue by rockersuke** [nataliapc/msx2daad#13]
Say we have this entry at PRO 5:

> XYZZY	_	MESSAGE "HEY HEY XYZZY!"

On running the game, typing "XYZZY" would output the message "HEY HEY XYZZY!" , which is OK... but it will be inmediaytely followed by a "No puedo hacer eso.", which is obvlously wrong (this very same code won't output "No puedo..." in any of the original DAAD terps).

At the very moment a condact is executed 'cause no condition has prevoiusly avoided it (in this case a MESSAGE condact) DAAD is aware that "something has been DONE" even when no DONE condact has been explicitly reached. That means the ISDONE condact at PRO 1 (right after we come back from PRO 5) equals to True, so REDO happens and the part of PRO 5 that invokes sysmess 8 ("No puedo...") is not reached.

This is not working in msax2daad, I mean, at least not the way it works in DAAD.

![01](https://user-images.githubusercontent.com/51891626/69287577-052ec400-0bf7-11ea-96a4-dabbfc09b82d.png)
![02](https://user-images.githubusercontent.com/51891626/69287591-0b24a500-0bf7-11ea-973a-45a18a98bb30.png)

[Ensayo DRC.zip](https://github.com/nataliapc/msx2daad/files/3872058/Ensayo.DRC.zip)

**Comment by nataliapc** [comment]
Seems fixed in the last commit, please check it.

If you need the compiled executable please contact me...

**Comment by nataliapc** [comment]
Not fixed yet...

**Comment by nataliapc** [comment]
ISDONE/ISNOTDONE is fixed finally.

In the next commit I will publish the bugfix.

Thanks!
