### ISSUE TITLE
Funcionamiento condacto WHATO

### ISSUE THREAD

**Issue by Dwalin77** [nataliapc/msx2daad#17]
En MSX2DAAD parece que WHATO funciona diferente que en los intérpretes clásicos.
En los intérpretes clásicos WHATO busca el nombre de un objeto en la sentencia actual y si lo encuentra, guarda el nº del objeto referenciado en la variable 51.
En MSX2DAAD parece que solo se guarda el nombre del objeto si el objeto está presente (llevado, puesto, aquí), pero no si no lo está.

**Comment by nataliapc** [comment]
Fixed at release 1.4
Thanks!
