### ISSUE TITLE
No reconoce como femeninos objetos que empiezan con "la"

### ISSUE THREAD

**Issue by Dwalin77** [nataliapc/msx2daad#19]
Si por ejemplo definimos un objeto como "la misteriosa llave", en lugar de "una misteriosa llave", el intérprete, a diferencia del intérprete clásico, no lo reconoce como femenino, y así, cuando la cogemos, por ejemplo, indica:
"Coges el misteriosa llave."

**Comment by nataliapc** [comment]
En la definición de objetos, estos deben empezar por `un` o `una` para que detecte su genero.
Revisaré el añadir también los artículos determinados.
