### ISSUE TITLE
Loading screen no carga y se cuelga

### ISSUE THREAD

**Issue by Utodev** [nataliapc/msx2daad#20]
Con el intérprete para SC8, pongo la imagen LOADING.SC8 en el disquete y se queda colgado, sin ella todo bien.

Adjunto DSK de ejemplo

[PRUEBA.zip](https://github.com/nataliapc/msx2daad/files/4500446/PRUEBA.zip)

**Comment by efraimsangil** [comment]
He descargado ese fichero y sustituido la imagen LOADING.SC8 por otra imagen de 256x212 y funciona perfectamente. Te lo muestro:
_LOADING.IM8 es la original y LOADING.IM8 es la que he puesto yo para probar y que funciona.
[PRUEBA.zip](https://github.com/nataliapc/msx2daad/files/4504563/PRUEBA.zip)

**Comment by nataliapc** [comment]
la imagen LOADING debe estar en formato IM8 para SC8, y con nombre `LOADING.IM8`, puedes convertir la imagen desde el formato SC8 a IM8 con `./bin/imgwizard.php`
