### ISSUE TITLE
INKEY is working?

### ISSUE THREAD

**Issue by cperezgrin** [nataliapc/msx2daad#23]
Hi, I have a process to read the key pressed from the player. I'm using DAAD Ready and it works for the rest of 8-bit systems, but with MSX2 the game doesn't wait for the key press.

This is the code. After calling this Process, the value of the key pressed should be in "fTeclaPulsada". It doesn't wait and it returns 0

> _           _   INKEY
                SKIP 1

> _           _   SKIP -2

> _           _   COPYFF fInkeyKey1 fTeclaPulsada

Am I doing something wrong or is there another way to read the input?
Thanks

**Comment by nataliapc** [comment]
Thanks for the report!
Will be fixed in the next commit.
