### ISSUE TITLE
NEWLINE después de un mensaje

### ISSUE THREAD

**Issue by SrHead** [nataliapc/msx2daad#24]
He observado que el intérprete de  msx2, antes de imprimir un mensaje, hace un  NEWLINE. Ocurre después de cualquier comando: INVE, COGER, etc

**Comment by nataliapc** [comment]
En realidad se producía un NEWLINE tras cada PARSE.
Ya está solucionado. Gracias!

**Comment by SrHead** [comment]
Gracias a ti, por tu trabajo. :)
