### ISSUE TITLE
Current object flags values if Current object is undefined

### ISSUE THREAD

**Issue by nataliapc** [nataliapc/msx2daad#5]
Which are the default **current object** flags values if undefined?

Flags affected: **CONum**, **COLoc**, **COCon**, **COWr**, **COAttr**, **COAttr2**

**Comment by rockersuke** [comment]
Para casos así yo suelo hacerme un proceso nuevo (pongamos que PRO 7) que haga algo como esto:

/PRO 7

> _       _     MESSAGE "RIGHT AFTER PARSE 0 IN PRO 1"
                NEWLINE
                MES "FLAG 51 (CONum):   "
                PRINT 51
                NEWLINE
                MES "FLAG 54 (COLoc):   "
                PRINT 54
                NEWLINE
                MES "FLAG 55 (COWei):   "
                PRINT 55
                NEWLINE
                MES "FLAG 56 (COCon):   "
                PRINT 56
                NEWLINE
                MES "FLAG 57 (COWr) :   "
                PRINT 57
                NEWLINE
                MES "FLAG 58 (COAttr):  "
                PRINT 58
                NEWLINE
                MES "FLAG 59 (COAttr2): "
                PRINT 29
                NEWLINE

Y luego lo llamo desde una nueva entrada en PRO 1 que esté justito después de la que hace el parseado:

> _       _     PARSE   0               ; Toma sentencia lógica del buffer
                PROCESS 2               ; Sentencia no válida o timeout
                REDO

> _       _     PROCESS 7

Compílalo para PC TEXT, ejecútalo con INTSD.EXE en dosbox y toma nota de lo que diga
[flags.zip](https://github.com/nataliapc/msx2daad/files/3872219/flags.zip)

**Comment by nataliapc** [comment]
Fixed at release 1.4
Thanks
