### ISSUE TITLE
Can't compile code after checkout

### ISSUE THREAD

**Issue by sndpl** [nataliapc/msx2daad#9]
After a checkout I can't compile the code because of 2 reasons:

1) libs directory is missing from the repository or not created
2) it expects an asm.lib file in the libs directory (I guess I need to compile https://github.com/Konamiman/MSX/tree/master/SRC/SDCC/asmlib and put the outcome it in the libs directory?)

for the rest, awesome work! I love the way you created the libs with each function in it's own file!

**Comment by nataliapc** [comment]
Thanks for your comments! :D

It's fixed now in the last commit.
The ./libs folder wasn't self created and the asm.lib was used in a very first version but not anymore.
